### ISSUE TITLE
More on Readme

### ISSUE THREAD

**Issue by athiraunni** [chaythanyanair/MongoApp#1]
Hi chay,
Can u add more detail on this readme. Actually I got interested by the name but could not get the idea yet. Hope you will update soon.

**Comment by chaythanyanair** [comment]
Actually  i started with this project just to learn the basics of JavaScript and MongoDB. But, due to certain reasons i couldn't complete it. I named the project so just because the app uses MongoDB. This is not a functional project, i will removing it from my Github repos soon. If you are interested in learning more about MongoDb and javaScript there are quite a lot of tutorials available online which will help you get started.

**Comment by athiraunni** [comment]
Thank you Chaythanya :)
